### ISSUE TITLE
Printout (both PDF and printer) is low resolution / blurry

### ISSUE THREAD

**Issue by roniyaniv** [HarelM/IsraelHiking#11]
[Israel Hiking Map.pdf](https://github.com/HarelM/IsraelHiking/files/847672/Israel.Hiking.Map.pdf)

See attached example of what I got as printout. It's blurry.

**Comment by HarelM** [comment]
Note that this is not a vector map, therefore the resolution is defined by the quality of the image we are generating. I don't think we can improve the quality without moving to vector format.
See issue here:
https://github.com/IsraelHikingMap/Map/issues/93
Here is a screenshot of the pdf file, I don't think the quality is poor or the image is blurry, it might not be in a good enough resolution for printing though...
![image](https://cloud.githubusercontent.com/assets/3269297/24018857/53456782-0a9e-11e7-8f52-e33b05ec913d.png)

**Comment by HarelM** [comment]
Also, this repository is obsolete, if we still feel strongly about it, please open an issue here:
https://github.com/IsraelHikingMap/Site/issues
