### ISSUE TITLE
Error running  IsraelHiking.mscript

### ISSUE THREAD

**Issue by ohadmanor** [HarelM/IsraelHiking#7]
Harel hi,

First it is great work you done here,

I'm try to learn how this works and when I run the IsraelHiking.mscript I get the following error:

Running the default script...
> use-ruleset alias=default
> add-web-map
READY
> open-script
   > // =======================================================
   > // === This script creates a OSM Hiking Map for Israel ===
   > // =======================================================
   > // ===============================
   > // === Start with an empty map ===
   > // ===============================
   > clear-map
   > // ===============================
   > // ==============================================================
   > // === restore the default for rendering the coastline & seas ===
   > // ==============================================================
   > set-setting name=map.coastline.mode value=loose
   > // ==============================================================
   > // =============================================================================
   > // === Load GeoFabric's Israel OSM map data snapshot downloaded from:        ===
   > // === http://download.geofabrik.de/asia/israel-and-palestine-latest.osm.pbf ===
   > // =============================================================================
   > load-source Cache\israel-and-palestine-latest.osm.pbf
      Read 5244936 nodes, 578707 ways and 4341 relations in total
   > // =============================================================================
   > // Temporarily hide the Israel OSM map data to speed up loading of subsequent sources
   > set-source index=1 visible=false
      Setting map source 'OSM file ('C:\Develope\IsraelHiking\Maperitive\Cache\israel-and-palestine-latest.osm.pbf')' visibility to False
   > // ===========================================================
   > // === Set the bounds according to the OSM snapshot bounds ===
   > // ===========================================================
   > geo-bounds-use-source
      Bounds were locked to source OSM file ('C:\Develope\IsraelHiking\Maperitive\Cache\israel-and-palestine-latest.osm.pbf'): 34.07929,29.37711,35.91531,33.35091
   > // ===========================================================
   > // ====================================================
   > // === Alternatively, rather than using GeoFabric's ===
   > // === snapshot, download from the overpass server  ===
   > // ====================================================
   > // set-geo-bounds 34.00842,29.32535,35.92745,33.398339999
   > // download-osm-overpass query="(node($b$);rel(bn)->.x;way($b$);node(w)->.x;rel(bw););out;"
   > // ========================================================
   > set-print-bounds-geo
      Set the printing bounds to '34.07929,29.37711,35.91531,33.35091'
   > // =======================================================
   > // === Set the printing bounds to match the map bounds ===
   > // =======================================================
   > geo-bounds-use-source
      Bounds were locked to source OSM file ('C:\Develope\IsraelHiking\Maperitive\Cache\israel-and-palestine-latest.osm.pbf'): 34.07929,29.37711,35.91531,33.35091
   > // =======================================================
   > // ===================================================
   > // === Add way lengths to the OSM data sources and ===
   > // === create Forest labels data in "Forests.osm"  ===
   > // ===================================================
   > run-python file="Python\AddWayLengthTags.py"
script-dir: C:\Develope\IsraelHiking\Maperitive\Python
> change-dir dir="C:\Develope\IsraelHiking\Maperitive\Python"
   > // ===================================================
   > // =======================================================================
   > // === Load the Forest labels data created using "AddWayLengthTags.py" ===
   > // =======================================================================
   > load-source Cache\Forests.osm
   SCRIPT FAILED
   Script execution error (line 57): The file does not exist

Do you have any idea what is the problem?

Thanks

Ohad

**Comment by HarelM** [comment]
Hi Ohad,

basically it sais that it can't find forests.osm which should be generated in AddWayLengthTags.py.
There is a problem with relative path in maperitive between two scripts we use: (the mscript and the python)
try running from inside maperitive the python script:
Python/CreateOruxMap.py
It might fail on creating the orux map with MOBAC but it should create the tiles.
Another alternative is to run AddWayLengthTags.py and make sure that the forests.osm is created under the cache folder.

it is worth fixing though - we don't use both script most of the time...

Harel M.

**Comment by HarelM** [comment]
Sorry, Bad merge, I have fixed it now, Please pull latest code.
commit: 79adb6d2db3ffeb52ebb10a3090dfca6d0d2c7d2

**Comment by ohadmanor** [comment]
It's OK,

I play around with the AddWayLengthTags.py, I'm not expert in python but I think there is problem in the following procedure can you figure it?

def escapeXML(text) :
    # Special Character   Escape Sequence Purpose  
    # &                   &amp;           Ampersand sign 
    # '                   &apos;          Single quote 
    # "                   &quot;          Double quote
    # >                   &gt;            Greater than 
    # <                   &lt;            Less than
    return text\
        .replace("&", "&amp;")\
        .replace("'", "&apos;")\
        .replace('"', "&quot;")\
        .replace(">", "&gt;")\
        .replace("<", "&lt;")

**Comment by zstadler** [comment]
Hi Ohad,

This procedure is responsible for proper quoting of certain characters in
the .osm XML file generated by the script.

Can you elaborate on what issue you see?

Zeev

**Comment by zstadler** [comment]
Note that the code, as seen in the email below, is not representative of the
code in github
<https://github.com/HarelM/IsraelHiking/blob/master/Maperitive/Python/AddWayLengthTags.py#L55>,
because of the quoting mechanism in XML.

[image: Inline image 1]

**Comment by ohadmanor** [comment]
well first as I say I'm newbie and I'm trying to understand this project.

if I do the simple procedure to run the script in the readme I get error.

I try to play around and when I do comment on this function it works . . So I guess it has a problem . . 

regarding to your second remark . . . yes it was changed when I send it . . .

**Comment by ohadmanor** [comment]
OK, sorry for the trouble I solve it,

the problem was with the language resource file in window 8.1

after fix it it works great!

**Comment by HarelM** [comment]
Hi Ohad,
Can you elaborate on what was the problem and how you fixed it? If this is something that might help others overcome this issue I'll add it to the readme page.

Thanks,
Harel M.

**Comment by ohadmanor** [comment]
My working environment not include Hebrew language support, when the python script get to Hebrew character it was in "gibberish" with the special charcters (&, ' , " , >) and the combination crash the script.

to resolve I simple add Hebrew support and everything works great.

**Comment by ohadmanor** [comment]
Harel / Zeev

I have a question do you know how to add a custom DTM in order to calculate the height contours?

If so, I have more accurate DEM so we can improve the maps significantly.

Ohad

**Comment by HarelM** [comment]
Check out this article:
http://maperitive.net/docs/Commands/SetDemSource.html
Maperitive should know how to handle custom dem data as long as it in a known format.
We currently use NASA's, and we converted it to a file called israel contours under cache folder.
If you are able to update this file with a better one please create a pull request and we'll check it out.

**Comment by ohadmanor** [comment]
I sew that page, but under "Using Your Own Custom DEM Sources" it's written "TODO"

what do you mean "create a pull request"?

**Comment by zstadler** [comment]
Can you elaborate on the source of the DEM? How do you know it's better?

**Comment by ohadmanor** [comment]
In short, the script use SRTM3 elevation data in 90m resolution, I have ASTER data elevation  - https://asterweb.jpl.nasa.gov which is 30m resolution (and it is from 2010 newer then 2000 SRTM3)

see this one: http://www2.jpl.nasa.gov/srtm/

I converted the data to standard DEM version so I hope we can use it for this project.

**Comment by zstadler** [comment]
I've already tried that in the end of 2013, according to the procedure here
<http://oruxmaps.foroactivos.net/t2757-altitude-and-3d-with-aster-gdem-tutorial>,
but the contours and hillshades were completely distorted/wrong.

See the discussion in the Maperitive forum
<https://groups.google.com/forum/#!msg/maperitive/V4EVWf2W3QI/LVogacsCGUIJ>

**Comment by zstadler** [comment]
By the way, you can retry the procedure below on a machine with more memory.

**Comment by ohadmanor** [comment]
Hi,

I toke us almost a year to convert ASTER data to standard DEM. I can imagine the distorted data.

regarding to what Igor Brejc done is based on the NASA STRM server so it wont help us too much because the ISRAEL area is old with low resolution.

If you know how to use a different DEM (I believe you have much more experience in maperitive scripts then I do) I can get you the data in any format that you need.to create the contours.

I attach sample of the DEM in 90m and one in 25m . . . 

![25](https://cloud.githubusercontent.com/assets/9347444/8406688/741b4992-1e67-11e5-941c-abbf4415f39b.jpg)

![90](https://cloud.githubusercontent.com/assets/9347444/8406676/43e9f598-1e67-11e5-93ae-9ae7cb3348b8.jpg)

**Comment by ohadmanor** [comment]
Some more examples . . . .
![ish](https://cloud.githubusercontent.com/assets/9347444/8407155/906e8f78-1e6c-11e5-808e-5adc430ca8bf.jpg)


![02](https://cloud.githubusercontent.com/assets/9347444/8407185/c7aa0ae4-1e6c-11e5-98ab-b4e1aa3288e6.jpg)

**Comment by zstadler** [comment]
Hi,

I've dug into my memory and my old files and found that eventually I took
Igor's advice at the end of the thread and I was able to create contour and
relief files from the ASTER files.
After examining the result, I decided to keep using the SRTM3 data because
the ASTER data was very noisy. For example, the contours and hillshade of
the Beit Nekofa Valley in zoom=14 look like:


​
and in zoom=15 without hill-shading:


​
​
Perhaps you've spent a year in reducing the noise, not in the format
conversion itself, right!?

Can you send me the DEM files so I can see how they look on the map?

Thanks,
Zeev

**Comment by ohadmanor** [comment]
In what format do need the DEM? and send me your mail I'll give you the access to google drive.

about the ASTER in contains temperature data and calculation according to the season that why to get it noise, you need to set a date for calculation.

**Comment by zstadler** [comment]
Hi,

I'm using the HGT file format. Please share it with zshtadler@gmail.com.

I don't remember ant references to temperature in the ASTER download or
conversion process ~2 yars ago.

In any case, looking forward to receive your files. How should I call this
collection?

Zeev
